name: Build test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on the machine
      uses: actions/checkout@v3
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "stanimirsergev99"

  ui-tests:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - name: Checkout the repository on the machine
        uses: actions/checkout@v3
      - name: Use Node.js version 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Start app
        run: npm start &
      - name: Run UI tests
        run: npm run test:ui
